In [1]:
from pathlib import Path
import pandas as pd

# Project root
PROJECT_ROOT = Path.cwd().parent

# Dataset paths
ONET_DIR = PROJECT_ROOT / "data" / "external" / "onet"
AISHE_DIR = PROJECT_ROOT / "data" / "external" / "aishe"
JOB_DIR = PROJECT_ROOT / "data" / "raw" / "archive (3)"

print("Project Root:", PROJECT_ROOT)
print("O*NET Folder:", ONET_DIR)
print("AISHE Folder:", AISHE_DIR)
print("Job Data Folder:", JOB_DIR)

Project Root: e:\Data_Analyst_Projects\Career_Intelligence_Education_Decision_Support
O*NET Folder: e:\Data_Analyst_Projects\Career_Intelligence_Education_Decision_Support\data\external\onet
AISHE Folder: e:\Data_Analyst_Projects\Career_Intelligence_Education_Decision_Support\data\external\aishe
Job Data Folder: e:\Data_Analyst_Projects\Career_Intelligence_Education_Decision_Support\data\raw\archive (3)

In [2]:
# O*NET files we expect
onet_files = [
    "occupation_data.csv",
    "essential_skills.csv",
    "transferable_skills.csv",
    "software_skills.csv",
    "education.csv",
    "training_and_experience.csv",
    "career_interest_types.csv",
    "related_occupations.csv",
    "job_titles.csv"
]

print("O*NET DATASET CHECK")
print("=" * 60)

for file_name in onet_files:
    file_path = ONET_DIR / file_name
    
    if file_path.exists():
        print(f"✅ {file_name}")
    else:
        print(f"❌ {file_name} — MISSING")

O*NET DATASET CHECK
============================================================
✅ occupation_data.csv
✅ essential_skills.csv
✅ transferable_skills.csv
✅ software_skills.csv
✅ education.csv
✅ training_and_experience.csv
✅ career_interest_types.csv
✅ related_occupations.csv
✅ job_titles.csv

In [3]:
# O*NET data quality check

for file_name in onet_files:
    file_path = ONET_DIR / file_name
    
    df = pd.read_csv(file_path, low_memory=False)
    
    print("\n" + "=" * 70)
    print(file_name)
    print("=" * 70)
    
    print(f"Rows              : {len(df):,}")
    print(f"Columns           : {len(df.columns)}")
    print(f"Missing values    : {df.isna().sum().sum():,}")
    print(f"Duplicate rows    : {df.duplicated().sum():,}")
    
    print("\nColumn names:")
    print(list(df.columns))

======================================================================
occupation_data.csv
======================================================================
Rows              : 1,016
Columns           : 3
Missing values    : 0
Duplicate rows    : 0

Column names:
['O*NET-SOC Code', 'Title', 'Description']

======================================================================
essential_skills.csv
======================================================================
Rows              : 18,200
Columns           : 15
Missing values    : 9,100
Duplicate rows    : 0

Column names:
['O*NET-SOC Code', 'Title', 'Element ID', 'Element Name', 'Scale ID', 'Scale Name', 'Data Value', 'N', 'Standard Error', 'Lower CI Bound', 'Upper CI Bound', 'Recommend Suppress', 'Not Relevant', 'Date', 'Domain Source']

======================================================================
transferable_skills.csv
======================================================================
Rows              : 45,500
Columns           : 15
Missing values    : 22,750
Duplicate rows    : 0

Column names:
['O*NET-SOC Code', 'Title', 'Element ID', 'Element Name', 'Scale ID', 'Scale Name', 'Data Value', 'N', 'Standard Error', 'Lower CI Bound', 'Upper CI Bound', 'Recommend Suppress', 'Not Relevant', 'Date', 'Domain Source']

======================================================================
software_skills.csv
======================================================================
Rows              : 31,821
Columns           : 7
Missing values    : 0
Duplicate rows    : 0

Column names:
['O*NET-SOC Code', 'Title', 'Workplace Example', 'Element ID', 'Element Name', 'Hot Technology', 'In Demand']

======================================================================
education.csv
======================================================================
Rows              : 11,495
Columns           : 15
Missing values    : 22,691
Duplicate rows    : 0

Column names:
['O*NET-SOC Code', 'Title', 'Element ID', 'Element Name', 'Scale ID', 'Scale Name', 'Category', 'Data Value', 'N', 'Standard Error', 'Lower CI Bound', 'Upper CI Bound', 'Recommend Suppress', 'Date', 'Domain Source']

======================================================================
training_and_experience.csv
======================================================================
Rows              : 26,812
Columns           : 15
Missing values    : 41,969
Duplicate rows    : 0

Column names:
['O*NET-SOC Code', 'Title', 'Element ID', 'Element Name', 'Scale ID', 'Scale Name', 'Category', 'Data Value', 'N', 'Standard Error', 'Lower CI Bound', 'Upper CI Bound', 'Recommend Suppress', 'Date', 'Domain Source']

======================================================================
career_interest_types.csv
======================================================================
Rows              : 8,307
Columns           : 9
Missing values    : 0
Duplicate rows    : 0

Column names:
['O*NET-SOC Code', 'Title', 'Element ID', 'Element Name', 'Scale ID', 'Scale Name', 'Data Value', 'Date', 'Domain Source']

======================================================================
related_occupations.csv
======================================================================
Rows              : 18,460
Columns           : 6
Missing values    : 0
Duplicate rows    : 0

Column names:
['O*NET-SOC Code', 'Title', 'Related O*NET-SOC Code', 'Related Title', 'Relatedness Tier', 'Index']

======================================================================
job_titles.csv
======================================================================
Rows              : 54,269
Columns           : 5
Missing values    : 49,814
Duplicate rows    : 0

Column names:
['O*NET-SOC Code', 'Title', 'Job Title', 'Short Title', 'Source(s)']

Cell 4 — Validate AISHE

In [4]:
# AISHE Excel validation

aishe_files = list(AISHE_DIR.glob("*.xlsx"))

print("AISHE DATASET CHECK")
print("=" * 60)

if len(aishe_files) == 0:
    print("❌ No AISHE Excel file found.")

else:
    for file_path in aishe_files:
        print(f"\nFile: {file_path.name}")
        
        excel_file = pd.ExcelFile(file_path)
        
        print(f"Number of sheets: {len(excel_file.sheet_names)}")
        
        print("\nSheet names:")
        for sheet in excel_file.sheet_names:
            print(f"  ✅ {sheet}")

AISHE DATASET CHECK
============================================================

File: AISHE Final Report 2023-24.xlsx
Number of sheets: 60

Sheet names:
  ✅ 1.UniNo
  ✅ 1a.InsResponse
  ✅ 2University-Specialisation
  ✅ 3Collegerange
  ✅ 4CollegeIndicator
  ✅ 5ManagementCollegeNo
  ✅ 6TotalEnr
  ✅ 6aTotalRegularEnr
  ✅ 6bTotalDistanceEnr
  ✅ 6cTotalPrivateEnr
  ✅ 6dTotalOnline
  ✅ 7UnivActwithConsUnit
  ✅ 8CollegeAct
  ✅ 9AllSAAct
  ✅ 9aSAILevel
  ✅ 10InstituionEst
  ✅ 11Programme
  ✅ 11a programme regular
  ✅ 11b ProgrammeDistance
  ✅ 12UGDisc
  ✅ 13PGDisc
  ✅ 14-15TotalEnrCategory (2)
  ✅ 16FS-countrylevel
  ✅ 17FS-statelevel
  ✅ 18FS-prog
  ✅ 19GER(2011)
  ✅ 20GPI2011
  ✅ 21TeacherCategory
  ✅ 22TeacherPost
  ✅ 22aTeacherPostUC
  ✅ 22bTeacherPostU
  ✅ 23StaffPost
  ✅ 24StaffCategory
  ✅ 25PTR
  ✅ 26UnivEnrolinclConstituentU
  ✅ 27 28 TypeEnrolmentCategory-Est
  ✅ 29TypeTeacherPostEstimated
  ✅ 30TypeTeacherCategoryEstimated
  ✅ 31Hostelstate
  ✅ 32TypeHostel
  ✅ 33 Out Turn
  ✅ 33 (a) Category Out Turn
  ✅ 34 Out Turn Prog
  ✅ Table 35 (34a E)
  ✅ 36 UG Discipline_35 E
  ✅ 37 PGDisc_36E
  ✅ 38Pop2020(2011)
  ✅ 39TypeStateUnivwithConsUnit
  ✅ 40NoUni
  ✅ 41NoUniType
  ✅ 42CollegeIndicator
  ✅ 43ENRLT 6
  ✅ 44ENRLR 6a
  ✅ 45EnrlCategory 14
  ✅ 46EnrlMinority 15
  ✅ 47GER  19
  ✅ 48GPI 20 Updated
  ✅ 49PTR 25
  ✅ 50LevelEnrlUniType
  ✅ 51PostTeacher

Cell 5 — Inspect Relevant AISHE Sheets

In [5]:
# Inspect only the AISHE sheets relevant to our project

relevant_sheets = [
    "2University-Specialisation",
    "3College",
    "6TotalEnr",
    "11Programme",
    "12UGDisc",
    "13PGDisc"
]

print("AISHE RELEVANT SHEETS")
print("=" * 70)

excel_file = pd.ExcelFile(aishe_files[0])

for sheet in relevant_sheets:
    
    if sheet in excel_file.sheet_names:
        
        df = pd.read_excel(
            aishe_files[0],
            sheet_name=sheet,
            nrows=5
        )
        
        print(f"\n{'=' * 70}")
        print(f"SHEET: {sheet}")
        print(f"{'=' * 70}")
        
        print(f"Columns: {len(df.columns)}")
        print("Column names:")
        print(list(df.columns))
        
        print("\nFirst 5 rows:")
        display(df.head())
        
    else:
        print(f"\n❌ Sheet not found: {sheet}")

AISHE RELEVANT SHEETS
======================================================================

======================================================================
SHEET: 2University-Specialisation
======================================================================
Columns: 20
Column names:
['Table 2.', 'Unnamed: 1', 'States/UTs & Specialisation-wise Number of Universities\n(Based on Actual Response)', 'Unnamed: 3', 'Unnamed: 4', 'Unnamed: 5', 'Unnamed: 6', 'Unnamed: 7', 'Unnamed: 8', 'Unnamed: 9', 'Unnamed: 10', 'States/UTs & Specialisation-wise Number of Universities\n(Based on Actual Response).1', 'Unnamed: 12', 'Unnamed: 13', 'Unnamed: 14', 'Unnamed: 15', 'Unnamed: 16', 'Unnamed: 17', 'Unnamed: 18', 'Unnamed: 19']

First 5 rows:

,Table 2.,Unnamed: 1,States/UTs & Specialisation-wise Number of Universities\n(Based on Actual Response),Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9,Unnamed: 10,States/UTs & Specialisation-wise Number of Universities\n(Based on Actual Response).1,Unnamed: 12,Unnamed: 13,Unnamed: 14,Unnamed: 15,Unnamed: 16,Unnamed: 17,Unnamed: 18,Unnamed: 19
0,Sl. No.,States/UTs,General,Agriculture,Design,Education,Fine Arts,Fisheries,Indian Language,Law,Management & Finance,Medical & paramedical,Rural Development,Science,Social Science,Sports/Yoga/Physical Education,Technical,Veterinary & Animal Sciences,Others,Grand Total
1,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20
2,1,Andhra Pradesh,24,2,1,0,1,1,3,1,1,3,0,2,0,0,12,1,0,52
3,2,Arunachal Pradesh,9,0,0,0,0,0,0,0,0,0,0,0,0,0,2,0,0,11
4,3,Assam,19,1,1,0,0,0,1,1,0,3,0,0,1,1,5,0,1,34

❌ Sheet not found: 3College

======================================================================
SHEET: 6TotalEnr
======================================================================
Columns: 29
Column names:
['Unnamed: 0', 'Unnamed: 1', 'Table 6. States/UTs-wise Estimated Enrolment at various levels', 'Unnamed: 3', 'Unnamed: 4', 'Unnamed: 5', 'Unnamed: 6', 'Unnamed: 7', 'Unnamed: 8', 'Unnamed: 9', 'Unnamed: 10', 'Table 6. States/UTs-wise Estimated Enrolment at various levels.1', 'Unnamed: 12', 'Unnamed: 13', 'Unnamed: 14', 'Unnamed: 15', 'Unnamed: 16', 'Unnamed: 17', 'Unnamed: 18', 'Unnamed: 19', 'Table 6. States/UTs-wise Estimated Enrolment at various levels.2', 'Unnamed: 21', 'Unnamed: 22', 'Unnamed: 23', 'Unnamed: 24', 'Unnamed: 25', 'Unnamed: 26', 'Unnamed: 27', 'Unnamed: 28']

First 5 rows:

,Unnamed: 0,Unnamed: 1,Table 6. States/UTs-wise Estimated Enrolment at various levels,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9,...,Unnamed: 19,Table 6. States/UTs-wise Estimated Enrolment at various levels.2,Unnamed: 21,Unnamed: 22,Unnamed: 23,Unnamed: 24,Unnamed: 25,Unnamed: 26,Unnamed: 27,Unnamed: 28
0,Sl No,States/UTs,Ph.D.,NaN,NaN,M.Phil.,NaN,NaN,Post Graduate,NaN,...,NaN,Certificate,NaN,NaN,Integrated,NaN,NaN,Grand Total,NaN,NaN
1,NaN,NaN,Male,Female,Total,Male,Female,Total,Male,Female,...,Total,Male,Female,Total,Male,Female,Total,Male,Female,Total
2,1,2,3,4,5,6,7,8,9,10,...,20,21,22,23,24,25,26,27,28,29
3,1,A & N Islands,NaN,NaN,NaN,NaN,NaN,NaN,492,813,...,678,NaN,NaN,NaN,48,131,179,3507,3621,7128
4,2,Andhra Pradesh,4490,3837,8327,NaN,NaN,NaN,99603.977205,103195.372681,...,144919,385,191,576,7512,4531,12043,929104.583099,875263.204145,1804367.787245

======================================================================
SHEET: 11Programme
======================================================================
Columns: 14
Column names:
['Table 11. Program-Wise Enrolment across different Social Groups  (All Modes of study) \n(Based on Actual Responses)', 'Unnamed: 1', 'Unnamed: 2', 'Unnamed: 3', 'Unnamed: 4', 'Unnamed: 5', 'Unnamed: 6', 'Unnamed: 7', 'Unnamed: 8', 'Unnamed: 9', 'Unnamed: 10', 'Unnamed: 11', 'Unnamed: 12', 'Unnamed: 13']

First 5 rows:

,Table 11. Program-Wise Enrolment across different Social Groups (All Modes of study) \n(Based on Actual Responses),Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9,Unnamed: 10,Unnamed: 11,Unnamed: 12,Unnamed: 13
0,Sl. No.,Programme,ALL,NaN,NaN,SCHEDULED CASTE,NaN,NaN,SCHEDULED TRIBE,NaN,NaN,OTHER BACKWARD CLASS,NaN,NaN
1,NaN,NaN,Male,Female,Total,Male,Female,Total,Male,Female,Total,Male,Female,Total
2,1,2,3,4,5,6,7,8,9,10,11,12,13,14
3,1,A.N.M.-Auxiliary Nurse & Midwife,1856,109356,111212,643,31378,32021,136,17951,18087,555,34304,34859
4,2,Acharya,12485,6194,18679,558,811,1369,212,326,538,1754,1977,3731

❌ Sheet not found: 12UGDisc

======================================================================
SHEET: 13PGDisc
======================================================================
Columns: 12
Column names:
['Unnamed: 0', 'Table 13.Enrolment Analysis by Major Disciplines/Subjects at Ph.D., M.Phil., and Postgraduate Levels (Based on Actual Responses)', 'Unnamed: 2', 'Unnamed: 3', 'Unnamed: 4', 'Unnamed: 5', 'Unnamed: 6', 'Unnamed: 7', 'Unnamed: 8', 'Unnamed: 9', 'Unnamed: 10', 'Unnamed: 11']

First 5 rows:

,Unnamed: 0,"Table 13.Enrolment Analysis by Major Disciplines/Subjects at Ph.D., M.Phil., and Postgraduate Levels (Based on Actual Responses)",Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9,Unnamed: 10,Unnamed: 11
0,Sl. \nNo.,Discipline,NaN,Ph.D.,NaN,NaN,M.Phil.,NaN,NaN,Post Graduate,NaN,NaN
1,NaN,NaN,NaN,Male,Female,Total,Male,Female,Total,Male,Female,Total
2,1,2,3,4,5,6,7,8,9,10,11,12
3,1,Agriculture,Agriculture,4816,4366,9182,NaN,NaN,NaN,22896,13175,36071
4,2,NaN,Forestry,348,416,764,NaN,NaN,NaN,628,711,1339

Task 5 — Final AISHE validation cell

In [6]:
# Find actual AISHE sheet names related to colleges, UG and PG

keywords = ["college", "ug", "under", "pg", "post"]

print("RELEVANT AISHE SHEETS")
print("=" * 70)

for sheet in excel_file.sheet_names:
    sheet_lower = sheet.lower()

    if any(keyword in sheet_lower for keyword in keywords):
        print("✅", sheet)

RELEVANT AISHE SHEETS
======================================================================
✅ 3Collegerange
✅ 4CollegeIndicator
✅ 5ManagementCollegeNo
✅ 8CollegeAct
✅ 12UGDisc
✅ 13PGDisc
✅ 22TeacherPost
✅ 22aTeacherPostUC
✅ 22bTeacherPostU
✅ 23StaffPost
✅ 29TypeTeacherPostEstimated
✅ 36 UG Discipline_35 E
✅ 37 PGDisc_36E
✅ 42CollegeIndicator
✅ 51PostTeacher

In [10]:
# ============================================================
# FIND JOB MARKET DATASET
# ============================================================

from pathlib import Path

PROJECT_DIR = Path(
    r"E:\Data_Analyst_Projects\Career_Intelligence_Education_Decision_Support"
)

print("Searching for postings.csv...")
print("=" * 70)

matches = list(PROJECT_DIR.rglob("postings.csv"))

if matches:
    print(f"Found {len(matches)} file(s):\n")

    for file in matches:
        size_gb = file.stat().st_size / (1024 ** 3)
        print("✅", file)
        print("   Size:", round(size_gb, 2), "GB")
else:
    print("❌ postings.csv was not found anywhere inside the project folder.")

Searching for postings.csv...
======================================================================
Found 1 file(s):

✅ E:\Data_Analyst_Projects\Career_Intelligence_Education_Decision_Support\data\raw\job_market\postings.csv
   Size: 0.48 GB

In [11]:
# ============================================================
# INSPECT JOB MARKET DATASET
# ============================================================

import pandas as pd

# Use the path Python found
POSTINGS_FILE = PROJECT_DIR / "data" / "raw" / "job_market" / "postings.csv"

# Read only a small sample
job_sample = pd.read_csv(
    POSTINGS_FILE,
    nrows=1000,
    low_memory=False
)

print("JOB MARKET SAMPLE")
print("=" * 70)

print("Rows loaded:", len(job_sample))
print("Columns:", len(job_sample.columns))

print("\nCOLUMN NAMES:")
for col in job_sample.columns:
    print("•", col)

print("\nFIRST 5 ROWS:")
display(job_sample.head())

JOB MARKET SAMPLE
======================================================================
Rows loaded: 1000
Columns: 31

COLUMN NAMES:
• job_id
• company_name
• title
• description
• max_salary
• pay_period
• location
• company_id
• views
• med_salary
• min_salary
• formatted_work_type
• applies
• original_listed_time
• remote_allowed
• job_posting_url
• application_url
• application_type
• expiry
• closed_time
• formatted_experience_level
• skills_desc
• listed_time
• posting_domain
• sponsored
• work_type
• currency
• compensation_type
• normalized_salary
• zip_code
• fips

FIRST 5 ROWS:

,job_id,company_name,title,description,max_salary,pay_period,location,company_id,views,med_salary,...,skills_desc,listed_time,posting_domain,sponsored,work_type,currency,compensation_type,normalized_salary,zip_code,fips
0,921716,Corcoran Sawyer Smith,Marketing Coordinator,Job descriptionA leading real estate firm in N...,20.0,HOURLY,"Princeton, NJ",2774458.0,20.0,NaN,...,Requirements: \n\nWe are seeking a College or ...,1.713398e+12,NaN,0,FULL_TIME,USD,BASE_SALARY,38480.0,8540.0,34021.0
1,1829192,NaN,Mental Health Therapist/Counselor,"At Aspen Therapy and Wellness , we are committ...",50.0,HOURLY,"Fort Collins, CO",NaN,1.0,NaN,...,NaN,1.712858e+12,NaN,0,FULL_TIME,USD,BASE_SALARY,83200.0,80521.0,8069.0
2,10998357,The National Exemplar,Assitant Restaurant Manager,The National Exemplar is accepting application...,65000.0,YEARLY,"Cincinnati, OH",64896719.0,8.0,NaN,...,We are currently accepting resumes for FOH - A...,1.713278e+12,NaN,0,FULL_TIME,USD,BASE_SALARY,55000.0,45202.0,39061.0
3,23221523,"Abrams Fensterman, LLP",Senior Elder Law / Trusts and Estates Associat...,Senior Associate Attorney - Elder Law / Trusts...,175000.0,YEARLY,"New Hyde Park, NY",766262.0,16.0,NaN,...,This position requires a baseline understandin...,1.712896e+12,NaN,0,FULL_TIME,USD,BASE_SALARY,157500.0,11040.0,36059.0
4,35982263,NaN,Service Technician,Looking for HVAC service tech with experience ...,80000.0,YEARLY,"Burlington, IA",NaN,3.0,NaN,...,NaN,1.713452e+12,NaN,0,FULL_TIME,USD,BASE_SALARY,70000.0,52601.0,19057.0

In [12]:
# ============================================================
# JOB MARKET — IMPORTANT COLUMN QUALITY CHECK
# ============================================================

important_cols = [
    "job_id",
    "company_name",
    "title",
    "description",
    "location",
    "skills_desc",
    "formatted_experience_level",
    "work_type",
    "remote_allowed",
    "min_salary",
    "max_salary",
    "normalized_salary",
    "currency",
    "listed_time",
    "job_posting_url"
]

quality = pd.DataFrame({
    "column": important_cols,
    "missing_count": [job_sample[col].isna().sum() for col in important_cols],
    "missing_percent": [
        round(job_sample[col].isna().mean() * 100, 2)
        for col in important_cols
    ],
    "data_type": [str(job_sample[col].dtype) for col in important_cols]
})

display(quality)

                        column  missing_count  missing_percent data_type
0                       job_id              0              0.0     int64
1                 company_name             92              9.2    object
2                        title              0              0.0    object
3                  description              0              0.0    object
4                     location              0              0.0    object
5                  skills_desc            989             98.9    object
6   formatted_experience_level            774             77.4    object
7                    work_type              0              0.0    object
8               remote_allowed            816             81.6   float64
9                   min_salary            662             66.2   float64
10                  max_salary            662             66.2   float64
11           normalized_salary            620             62.0   float64
12                    currency            620             62.0    object
13                 listed_time              0              0.0   float64
14             job_posting_url              0              0.0    object

In [13]:
# ============================================================
# FINAL JOB MARKET VALIDATION
# ============================================================

print("JOB MARKET FINAL CHECK")
print("=" * 70)

print("Total rows:", len(job_sample))
print("Total columns:", len(job_sample.columns))

print("\nRequired columns:")
required_cols = [
    "job_id",
    "title",
    "description",
    "location",
    "work_type",
    "job_posting_url"
]

for col in required_cols:
    print(f"{'✅' if col in job_sample.columns else '❌'} {col}")

print("\nDuplicate job IDs:", job_sample["job_id"].duplicated().sum())

print("\nUnique job titles:", job_sample["title"].nunique())

print("\nTop 15 job titles:")
print(job_sample["title"].value_counts().head(15))

JOB MARKET FINAL CHECK
======================================================================
Total rows: 1000
Total columns: 31

Required columns:
✅ job_id
✅ title
✅ description
✅ location
✅ work_type
✅ job_posting_url

Duplicate job IDs: 0

Unique job titles: 901

Top 15 job titles:
title
Account Executive                  6
Project Manager                    6
Associate Attorney                 6
Administrative Assistant           5
Construction Project Manager       4
Staff Accountant                   4
Customer Service Representative    4
Marketing Manager                  4
Manufacturing Engineer             3
Full Stack Engineer                3
Salesperson                        3
Store Manager                      3
Project Engineer                   3
Software Engineer                  3
Accounting Manager                 3
Name: count, dtype: int64